import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const repoRoot = process.cwd();
const publicDataRoot = join(repoRoot, "src", "data");
const generatedOptionsPath = join(repoRoot, "src", "lib", "options.generated.ts");

function readJson(p) {
  return JSON.parse(readFileSync(p, "utf8"));
}

function getYearsFromManifest() {
  const manifestPath = join(publicDataRoot, "manifest.json");
  if (!existsSync(manifestPath)) {
    console.warn(`No manifest found at ${manifestPath}`);
    return [];
  }

  const manifest = readJson(manifestPath);
  return manifest.years;
}

function buildOffenseNamesByYear(years) {
  const sortedYears = [...years].sort((a, b) => Number(a) - Number(b));
  const out = {};
  for (const year of sortedYears) {
    const offenseTypesPath = join(publicDataRoot, String(year), "offenseTypes.json");
    if (!existsSync(offenseTypesPath)) {
      console.warn(`Missing ${offenseTypesPath}`);
      continue;
    }
    const offenseTypes = readJson(offenseTypesPath);
    const byCode = {};
    for (const o of offenseTypes ?? []) {
      const code = String(o?.offenseCode ?? "").trim();
      const name = String(o?.offenseName ?? "").trim();
      if (code && name) byCode[code] = name;
    }
    out[String(year)] = byCode;
  }
  return out;
}

function writeGeneratedOptions({ years, offenseCodes, offenseNamesByYearAndCode }) {
  const yearOptions = years.map(Number).sort((a, b) => a - b);
  const offenseCodeOptions = ["all", ...offenseCodes];

  const file = `// This file is generated by scripts/generate.mjs

export const yearOptions = ${JSON.stringify(yearOptions, null, 2)} as const;

export const offenseCodeOptions = ${JSON.stringify(offenseCodeOptions, null, 2)} as const;

export const offenseNamesByYearAndCode = ${JSON.stringify(offenseNamesByYearAndCode, null, 2)} as const;
`;

  writeFileSync(generatedOptionsPath, file);
}

async function main() {
  const years = getYearsFromManifest();
  const latest = years.at(-1);
  if (!latest) {
    console.warn(`No year folders found under ${publicDataRoot}`);
    return;
  }

  const yearDir = join(publicDataRoot, latest);
  const offenseTypesPath = join(yearDir, "offenseTypes.json");

  const offenseTypes = readJson(offenseTypesPath);

  const offenseCodes = [
    ...new Set((offenseTypes ?? []).map((o) => String(o?.offenseCode)).filter(Boolean)),
  ].sort();

  const offenseNamesByYearAndCode = buildOffenseNamesByYear(years);

  writeGeneratedOptions({
    years,
    offenseCodes,
    offenseNamesByYearAndCode,
  });

  console.log(
    `[Generate] Successfully generated options for ${years.length} years and ${offenseCodes.length} offense codes`,
  );
}

await main();
